<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use mysql_xdevapi\TableDelete;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // \App\Models\User::factory(10)->create();

        // \App\Models\User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);

        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'nhat',
                'email' => 'hoangnhathn1702@gmail.com',
                'password' => Hash::make('123456'),
                'avatar' => null,
                'level' => 0,
                'description' =>null,

                'country' => 'Việt Nam',
                'street_address' => 'Xuân Phương, Nam Từ Liêm, Hà Nội',
                'postcode_zip' => '10000',
                'town_city' => 'Hà Nội',
                'phone' => '0123456789',
            ],
            [
                'id' => 2,
                'name' => 'nga',
                'email' => 'ptnga@gmail.com',
                'password' => Hash::make('123456'),
                'avatar' => null,
                'level' => 0,
                'description' =>null,

                'country' => 'Việt Nam',
                'street_address' => 'Xuân Phương, Nam Từ Liêm, Hà Nội',
                'postcode_zip' => '10000',
                'town_city' => 'Hà Nội',
                'phone' => '0123456789',
            ],
            [
                'id' => 3,
                'name' => 'admin',
                'email' => 'admin@gmail.com',
                'password' => Hash::make('123456'),
                'avatar' => null,
                'level' => 0,
                'description' =>null,

                'country' => 'Việt Nam',
                'street_address' => 'Xuân Phương, Nam Từ Liêm, Hà Nội',
                'postcode_zip' => '10000',
                'town_city' => 'Hà Nội',
                'phone' => '0123456789',
            ],
            [
                'id' => 4,
                'name' => 'test',
                'email' => 'test@gmail.com',
                'password' => Hash::make('123456'),
                'avatar' => null,
                'level' => 2,
                'description' =>null,

                'country' => 'Việt Nam',
                'street_address' => 'Xuân Phương, Nam Từ Liêm, Hà Nội',
                'postcode_zip' => '10000',
                'town_city' => 'Hà Nội',
                'phone' => '0123456789',
            ]
            ]);

            DB::table('slider')->insert([
               [
                   'id' => 1,
                   'path' => 'slider1.png',
               ],
                [
                    'id' => 2,
                    'path' => 'slider2.png',
                ],
                [
                    'id' => 3,
                    'path' => 'slider3.png',
                ],
                [
                    'id' => 4,
                    'path' => 'slider4.png',
                ]
            ]);

            DB::table('blogs')->insert([
                [
                    'user_id' => 3,
                    'title' => 'Hòa Bình phát động Tháng cao điểm ủng hộ xây dựng Quỹ “Vì người nghèo” năm 2022',
                    'image' => 'blog1.png',
                    'category' => 'Company',
                    'content' => '',
                ],
                [
                    'user_id' => 3,
                    'title' => 'BUỔI GẶP MẶT ĐẶC BIỆT TẠI NHÀ MÁY XE ĐẠP THỐNG NHẤT',
                    'image' => 'blog2.png',
                    'category' => 'CodeLeanON',
                    'content' => '',
                ],
                [
                    'user_id' => 3,
                    'title' => '2000KM ĐẠP XE XUYÊN VIỆT Ở TUỔI 61 VỚI “0” LẦN SỬA XE',
                    'image' => 'blog3.png',
                    'category' => 'TRAVEL',
                    'content' => '',
                ],
            ]);


            DB::table('brands')->insert([
                [
                    'name' => 'Thống Nhất',
                ],
                [
                    'name' => 'Honda',
                ],
                [
                    'name' => 'Yamaha',
                ],

            ]);


            DB::table('products_category')->insert([
                [
                    'category_name' => 'Xe đạp trẻ em',
                ],
                [
                    'category_name' => 'Xe đạp người lớn',
                ],
                [
                    'category_name' => 'Xe đạp thể thao',
                ],
                [
                    'category_name' => 'Xe máy',
                ],
                [
                    'category_name' => 'Xe ga',
                ],
                [
                    'category_name' => 'Xe côn tay',
                ],
            ]);

            DB::table('products')->insert([
                [
                    'id' => 1,
                    'brand_id' => 1,
                    'category_id' => 1,
                    'product_name' => 'Princess 12″',
                    'description' => '',
                    'content' => '',
                    'price' => 1890000,
                    'qty' => 20,
                    'discount' => 1790000,
                    'weight' => 10,
                    'sku' => '00012',
                    'featured' => true,
                    'tag' => 'Bicycle',
                ],
                [
                    'id' => 2,
                    'brand_id' => 1,
                    'category_id' => 2,
                    'product_name' => 'M 26″-01',
                    'description' => null,
                    'content' => null,
                    'price' => 3690000,
                    'qty' => 20,
                    'discount' => null,
                    'weight' => 15,
                    'sku' => '00013',
                    'featured' => true,
                    'tag' => 'Bicycle',
                ],
                [
                    'id' => 3,
                    'brand_id' => 1,
                    'category_id' => 2,
                    'product_name' => 'SLX 26-01',
                    'description' => null,
                    'content' => null,
                    'price' => 6650000,
                    'qty' => 20,
                    'discount' => null,
                    'weight' => 15,
                    'sku' => '00014',
                    'featured' => true,
                    'tag' => 'Bicycle',
                ],
                [
                    'id' => 4,
                    'brand_id' => 1,
                    'category_id' => 2,
                    'product_name' => 'New 24″',
                    'description' => null,
                    'content' => null,
                    'price' => 2450000,
                    'qty' => 20,
                    'discount' => null,
                    'weight' => 15,
                    'sku' => '00014',
                    'featured' => true,
                    'tag' => 'Bicycle',
                ],
                [
                    'id' => 5,
                    'brand_id' => 1,
                    'category_id' => 3,
                    'product_name' => "MTB 20″ – 03",
                    'description' => null,
                    'content' => null,
                    'price' => 1990000,
                    'qty' => 20,
                    'discount' => null,
                    'weight' => 11.25,
                    'sku' => '00015',
                    'featured' => false,
                    'tag' => 'Bicycle',
                ],
                [
                    'id' => 6,
                    'brand_id' => 1,
                    'category_id' => 1,
                    'product_name' => 'Princess 16″',
                    'description' => null,
                    'content' => null,
                    'price' => 2090000,
                    'qty' => 20,
                    'discount' => null,
                    'weight' => 10,
                    'sku' => '00016',
                    'featured' => true,
                    'tag' => 'Bicycle',
                ],
                [
                    'id' => 7,
                    'brand_id' => 1,
                    'category_id' => 1,
                    'product_name' => 'Kitten 20″',
                    'description' => null,
                    'content' => null,
                    'price' => 2390000,
                    'qty' => 20,
                    'discount' => null,
                    'weight' => 10,
                    'sku' => '00017',
                    'featured' => true,
                    'tag' => 'Bicycle',
                ],
                [
                    'id' => 8,
                    'brand_id' => 1,
                    'category_id' => 1,
                    'product_name' => 'Neo 20″ – 04',
                    'description' => null,
                    'content' => null,
                    'price' => 2190000,
                    'qty' => 20,
                    'discount' => null,
                    'weight' => 10,
                    'sku' => '00018',
                    'featured' => true,
                    'tag' => 'Bicycle',
                ],
                [
                    'id' => 9,
                    'brand_id' => 1,
                    'category_id' => 1,
                    'product_name' => 'TE 16″ – 02',
                    'description' => null,
                    'content' => null,
                    'price' => 2090000,
                    'qty' => 20,
                    'discount' => null,
                    'weight' => 10,
                    'sku' => '00019',
                    'featured' => true,
                    'tag' => 'Bicycle',
                ],
                [
                    'id' => 10,
                    'brand_id' => 2,
                    'category_id' => 4,
                    'product_name' => 'Honda Wave RSX Fi 110',
                    'description' => null,
                    'content' => null,
                    'price' => 26500000,
                    'qty' => 20,
                    'discount' => null,
                    'weight' => 50,
                    'sku' => '00020',
                    'featured' => true,
                    'tag' => 'Motobike',
                ],
                [
                    'id' => 11,
                    'brand_id' => 3,
                    'category_id' => 5,
                    'product_name' => 'Yamaha Janus',
                    'description' => null,
                    'content' => null,
                    'price' => 28600000,
                    'qty' => 20,
                    'discount' => null,
                    'weight' => 50,
                    'sku' => '00021',
                    'featured' => true,
                    'tag' => 'Motobike',
                ],
                [
                    'id' => 12,
                    'brand_id' => 2,
                    'category_id' => 6,
                    'product_name' => 'Honda Winner X',
                    'description' => null,
                    'content' => null,
                    'price' => 329900000,
                    'qty' => 20,
                    'discount' => null,
                    'weight' => 50,
                    'sku' => '00022',
                    'featured' => true,
                    'tag' => 'Motobike',
                ],
                [
                    'id' => 13,
                    'brand_id' => 1,
                    'category_id' => 2,
                    'product_name' => 'GN 05-26”',
                    'description' => null,
                    'content' => null,
                    'price' => 2390000,
                    'qty' => 50,
                    'discount' => null,
                    'weight' => 15,
                    'sku' => '00023',
                    'featured' => true,
                    'tag' => 'Bicycle',
                ],
                [
                    'id' => 14,
                    'brand_id' => 1,
                    'category_id' => 2,
                    'product_name' => 'GN 06-26”',
                    'description' => null,
                    'content' => null,
                    'price' => 2250000,
                    'qty' => 50,
                    'discount' => null,
                    'weight' => 15,
                    'sku' => '00024',
                    'featured' => true,
                    'tag' => 'Bicycle',
                ],
                [
                    'id' => 15,
                    'brand_id' => 1,
                    'category_id' => 3,
                    'product_name' => 'MTB 24″-03',
                    'description' => null,
                    'content' => null,
                    'price' => 2550000,
                    'qty' => 50,
                    'discount' => null,
                    'weight' => 15,
                    'sku' => '00025',
                    'featured' => true,
                    'tag' => 'Bicycle',
                ],
                [
                    'id' => 16,
                    'brand_id' => 1,
                    'category_id' => 3,
                    'product_name' => 'M 26″-01',
                    'description' => null,
                    'content' => null,
                    'price' => 3690000,
                    'qty' => 50,
                    'discount' => null,
                    'weight' => 15,
                    'sku' => '00026',
                    'featured' => true,
                    'tag' => 'Bicycle',
                ],
                [
                    'id' => 17,
                    'brand_id' => 1,
                    'category_id' => 3,
                    'product_name' => 'SLX 26-01',
                    'description' => null,
                    'content' => null,
                    'price' => 6650000,
                    'qty' => 50,
                    'discount' => null,
                    'weight' => 15,
                    'sku' => '00027',
                    'featured' => true,
                    'tag' => 'Bicycle',
                ],
                [
                    'id' => 18,
                    'brand_id' => 1,
                    'category_id' => 3,
                    'product_name' => 'SLX 27,5-01',
                    'description' => null,
                    'content' => null,
                    'price' => 6750000,
                    'qty' => 50,
                    'discount' => null,
                    'weight' => 15,
                    'sku' => '00028',
                    'featured' => true,
                    'tag' => 'Bicycle',
                ],
                [
                    'id' => 19,
                    'brand_id' => 2,
                    'category_id' => 4,
                    'product_name' => 'Blade 2023',
                    'description' => null,
                    'content' => null,
                    'price' => 19250000,
                    'qty' => 50,
                    'discount' => null,
                    'weight' => 50,
                    'sku' => '00029',
                    'featured' => true,
                    'tag' => 'Motobike',
                ],
                [
                    'id' => 20,
                    'brand_id' => 2,
                    'category_id' => 4,
                    'product_name' => 'Future 125 FI',
                    'description' => null,
                    'content' => null,
                    'price' => 31090000,
                    'qty' => 50,
                    'discount' => null,
                    'weight' => 50,
                    'sku' => '00030',
                    'featured' => true,
                    'tag' => 'Motobike',
                ],
                [
                    'id' => 21,
                    'brand_id' => 3,
                    'category_id' => 4,
                    'product_name' => 'JUPITER FI MÀU MỚI',
                    'description' => null,
                    'content' => null,
                    'price' => 30800000,
                    'qty' => 50,
                    'discount' => null,
                    'weight' => 50,
                    'sku' => '00031',
                    'featured' => true,
                    'tag' => 'Motobike',
                ],
                [
                    'id' => 22,
                    'brand_id' => 3,
                    'category_id' => 4,
                    'product_name' => 'JUPITER FI',
                    'description' => null,
                    'content' => null,
                    'price' => 30600000,
                    'qty' => 50,
                    'discount' => null,
                    'weight' => 50,
                    'sku' => '00032',
                    'featured' => true,
                    'tag' => 'Motobike',
                ],
                [
                    'id' => 23,
                    'brand_id' => 2,
                    'category_id' => 5,
                    'product_name' => 'Vision',
                    'description' => null,
                    'content' => null,
                    'price' => 31690000,
                    'qty' => 50,
                    'discount' => null,
                    'weight' => 50,
                    'sku' => '00033',
                    'featured' => true,
                    'tag' => 'Motobike',
                ],
                [
                    'id' => 24,
                    'brand_id' => 2,
                    'category_id' => 5,
                    'product_name' => 'Honda VARIO 160',
                    'description' => null,
                    'content' => null,
                    'price' => 51990000,
                    'qty' => 50,
                    'discount' => null,
                    'weight' => 50,
                    'sku' => '00034',
                    'featured' => true,
                    'tag' => 'Motobike',
                ],
                [
                    'id' => 25,
                    'brand_id' => 3,
                    'category_id' => 5,
                    'product_name' => 'FREEGO S PHIÊN BẢN ĐẶC BIỆT MÀU MỚI',
                    'description' => null,
                    'content' => null,
                    'price' => 347000000,
                    'qty' => 50,
                    'discount' => null,
                    'weight' => 50,
                    'sku' => '00035',
                    'featured' => true,
                    'tag' => 'Motobike',
                ],
                [
                    'id' => 26,
                    'brand_id' => 3,
                    'category_id' => 5,
                    'product_name' => 'GRANDE PHIÊN BẢN GIỚI HẠN HOÀN TOÀN MỚI',
                    'description' => null,
                    'content' => null,
                    'price' => 52200000,
                    'qty' => 50,
                    'discount' => null,
                    'weight' => 50,
                    'sku' => '00036',
                    'featured' => true,
                    'tag' => 'Motobike',
                ],
                [
                    'id' => 27,
                    'brand_id' => 2,
                    'category_id' => 6,
                    'product_name' => 'CBR150R',
                    'description' => null,
                    'content' => null,
                    'price' => 72290000,
                    'qty' => 50,
                    'discount' => null,
                    'weight' => 50,
                    'sku' => '00037',
                    'featured' => true,
                    'tag' => 'Motobike',
                ],
                [
                    'id' => 28,
                    'brand_id' => 2,
                    'category_id' => 6,
                    'product_name' => 'CB150R The Streetster',
                    'description' => null,
                    'content' => null,
                    'price' => 105500000,
                    'qty' => 50,
                    'discount' => null,
                    'weight' => 50,
                    'sku' => '00038',
                    'featured' => true,
                    'tag' => 'Motobike',
                ],
                [
                    'id' => 29,
                    'brand_id' => 3,
                    'category_id' => 6,
                    'product_name' => 'XS155R',
                    'description' => null,
                    'content' => null,
                    'price' => 77000000,
                    'qty' => 50,
                    'discount' => null,
                    'weight' => 50,
                    'sku' => '00039',
                    'featured' => true,
                    'tag' => 'Motobike',
                ],
                [
                    'id' => 30,
                    'brand_id' => 3,
                    'category_id' => 6,
                    'product_name' => 'MT-03',
                    'description' => null,
                    'content' => null,
                    'price' => 129000000,
                    'qty' => 50,
                    'discount' => null,
                    'weight' => 50,
                    'sku' => '00040',
                    'featured' => true,
                    'tag' => 'Motobike',
                ],
            ]);

            DB::table('products_images')->insert([
                [
                    'product_id' => 1,
                    'path' => 'product1_1.png',
                ],
                [
                    'product_id' => 1,
                    'path' => 'product1_2.png',
                ],
                [
                    'product_id' => 1,
                    'path' => 'product1_3.png',
                ],
                [
                    'product_id' => 2,
                    'path' => 'product2_1.png',
                ],
                [
                    'product_id' => 2,
                    'path' => 'product2_2.png',
                ],
                [
                    'product_id' => 2,
                    'path' => 'product2_2.png',
                ],
                [
                    'product_id' => 3,
                    'path' => 'product3_1.png',
                ],
                [
                    'product_id' => 3,
                    'path' => 'product3_2.png',
                ],
                [
                    'product_id' => 3,
                    'path' => 'product3_3.png',
                ],
                [
                    'product_id' => 4,
                    'path' => 'product4_1.png',
                ],
                [
                    'product_id' => 4,
                    'path' => 'product4_2.png',
                ],
                [
                    'product_id' => 4,
                    'path' => 'product4_3.png',
                ],
                [
                    'product_id' => 5,
                    'path' => 'product5_1.png',
                ],
                [
                    'product_id' => 5,
                    'path' => 'product5_2.png',
                ],
                [
                    'product_id' => 5,
                    'path' => 'product5_3.png',
                ],
                [
                    'product_id' => 6,
                    'path' => 'product6_1.png',
                ],
                [
                    'product_id' => 6,
                    'path' => 'product6_2.png',
                ],
                [
                    'product_id' => 6,
                    'path' => 'product6_3.png',
                ],
                [
                    'product_id' => 7,
                    'path' => 'product7_1.png',
                ],
                [
                    'product_id' => 7,
                    'path' => 'product7_2.png',
                ],
                [
                    'product_id' => 7,
                    'path' => 'product7_3.png',
                ],
                [
                    'product_id' => 8,
                    'path' => 'product8_1.png',
                ],
                [
                    'product_id' => 8,
                    'path' => 'product8_2.png',
                ],
                [
                    'product_id' => 8,
                    'path' => 'product8_3.png',
                ],
                [
                    'product_id' => 9,
                    'path' => 'product9_1.png',
                ],
                [
                    'product_id' => 9,
                    'path' => 'product9_2.png',
                ],
                [
                    'product_id' => 9,
                    'path' => 'product9_3.png',
                ],
                [
                    'product_id' => 10,
                    'path' => 'product10_1.png',
                ],
                [
                    'product_id' => 10,
                    'path' => 'product10_2.png',
                ],
                [
                    'product_id' => 11,
                    'path' => 'product11_1.png',
                ],
                [
                    'product_id' => 11,
                    'path' => 'product11_2.png',
                ],
                [
                    'product_id' => 12,
                    'path' => 'product12_1.png',
                ],
                [
                    'product_id' => 12,
                    'path' => 'product12_2.png',
                ],
                [
                    'product_id' => 13,
                    'path' => 'product13_1.png',
                ],
                [
                    'product_id' => 14,
                    'path' => 'product14_1.png',
                ],
                [
                    'product_id' => 15,
                    'path' => 'product15_1.png',
                ],
                [
                    'product_id' => 16,
                    'path' => 'product16_1.png',
                ],
                [
                    'product_id' => 17,
                    'path' => 'product17_1.png',
                ],
                [
                    'product_id' => 18,
                    'path' => 'product18_1.png',
                ],
                [
                    'product_id' => 19,
                    'path' => 'product19_1.png',
                ],
                [
                    'product_id' => 20,
                    'path' => 'product20_1.png',
                ],
                [
                    'product_id' => 21,
                    'path' => 'product21_1.png',
                ],
                [
                    'product_id' => 22,
                    'path' => 'product22_1.png',
                ],
                [
                    'product_id' => 23,
                    'path' => 'product23_1.png',
                ],
                [
                    'product_id' => 24,
                    'path' => 'product24_1.png',
                ],
                [
                    'product_id' => 25,
                    'path' => 'product25_1.png',
                ],
                [
                    'product_id' => 26,
                    'path' => 'product26_1.png',
                ],
                [
                    'product_id' => 27,
                    'path' => 'product27_1.png',
                ],
                [
                    'product_id' => 28,
                    'path' => 'product28_1.png',
                ],
                [
                    'product_id' => 29,
                    'path' => 'product29_1.png',
                ],
                [
                    'product_id' => 30,
                    'path' => 'product30_1.png',
                ],
            ]);

            DB::table('products_details')->insert([
                [
                    'product_id' => 1,
                    'color' => 'Đỏ',
                    'size' => '12',
                    'qty' => 5,
                ],
                [
                    'product_id' => 1,
                    'color' => 'Hồng',
                    'size' => '12',
                    'qty' => 5,
                ],
                [
                    'product_id' => 1,
                    'color' => 'Tím',
                    'size' => '12',
                    'qty' => 10,
                ],
            ]);

            DB::table('products_comments')->insert([
                [
                    'product_id' => 1,
                    'user_id' => 4,
                    'email' => 'BrandonKelley@gmail.com',
                    'name' => 'Brandon Kelley',
                    'messages' => 'Nice !',
                    'rating' => 4,
                ],
                [
                    'product_id' => 1,
                    'user_id' => 5,
                    'email' => 'RoyBanks@gmail.com',
                    'name' => 'Roy Banks',
                    'messages' => 'Nice !',
                    'rating' => 4,
                ],
            ]);
    }
}
